Addition of important terms to course schedule.
OS-Sketch/www.os-sketch.com pull request #64
Opened 2022-12-13 00:59 UTC by zaethovenn

What I did was add definitions to chapters 2-16 to bring all of their definition counts to 5 per section. There are 15 following chapters that will need updating to kapfhammers 5 count per section request.

2022-12-13 01:21 UTC, burgess01 requested changes
There are some small formatting issues that I would like you to fix before this is merged. Also, for some reason, this PR does not have a preview build. If you would be able to get one so we can see how this will look when it is merged into main I would really appreciate that, thank you!

2022-12-13 01:21 UTC, burgess01 commented on docs/operating-systems/schedule.md
> +    - **journaling** - also known as copy-on-write, is a special ordering protocol
capitalize term to match the rest of the existing entries

2022-12-13 01:21 UTC, burgess01 commented on docs/operating-systems/schedule.md
> +    - **malloc()** - you pass malloc a size you request for room on the heap that either passes you a pointer to your newly allocated space or fails and returns NULL
capitalize term to match the rest of the existing entries, also remove parenthesis as you don't include them for other function terms like fork

2022-12-13 01:35 UTC, burgess01 approved these changes
This looks great!

2022-12-13 01:36 UTC, merged

2022-12-15 03:07 UTC, gkapfham commented
Note: This PR had the correct links for the semaphores content.

2022-12-15 03:08 UTC, gkapfham commented
Note: this PR had the correct link for the semaphores content.